"""Closed enumerations for the Phase 2 interpretation boundary."""

from enum import Enum


class KnowledgeReviewStatus(str, Enum):
    CANONICAL_ONLY = "CANONICAL_ONLY"
    DRAFT = "DRAFT"
    REVIEWED = "REVIEWED"
    APPROVED = "APPROVED"


class QuestionDomain(str, Enum):
    RELATIONSHIP = "RELATIONSHIP"
    CAREER = "CAREER"
    FINANCE_COOPERATION = "FINANCE_COOPERATION"


class ConclusionLevel(str, Enum):
    CLEARLY_FAVORABLE = "CLEARLY_FAVORABLE"
    CONDITIONALLY_FAVORABLE = "CONDITIONALLY_FAVORABLE"
    MIXED_OR_UNSETTLED = "MIXED_OR_UNSETTLED"
    CLEARLY_UNFAVORABLE = "CLEARLY_UNFAVORABLE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class EvidenceSufficiency(str, Enum):
    SUFFICIENT = "SUFFICIENT"
    LIMITED = "LIMITED"
    INSUFFICIENT = "INSUFFICIENT"


class ClaimKind(str, Enum):
    HEXAGRAM_INTERPRETATION = "HEXAGRAM_INTERPRETATION"
    REAL_WORLD_CONTEXT = "REAL_WORLD_CONTEXT"
    ACTION_RECOMMENDATION = "ACTION_RECOMMENDATION"
    UNCERTAINTY = "UNCERTAINTY"
    TIMING_LIMITATION = "TIMING_LIMITATION"


class ServiceStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED_VALIDATION = "FAILED_VALIDATION"
    PROVIDER_FAILED = "PROVIDER_FAILED"


class RelationPhase(str, Enum):
    INITIAL = "INITIAL"
    CHANGED = "CHANGED"


class RelationDirection(str, Enum):
    FAVORABLE = "FAVORABLE"
    MIXED = "MIXED"
    UNFAVORABLE = "UNFAVORABLE"


class KnowledgeAccessMode(str, Enum):
    PRODUCTION = "PRODUCTION"
    INTERNAL_REVIEW = "INTERNAL_REVIEW"
    INTERNAL_DRAFT_PREVIEW = "INTERNAL_DRAFT_PREVIEW"


class NarrativeKind(str, Enum):
    EXPLANATION = "EXPLANATION"
    ACTION_OPTION = "ACTION_OPTION"
    CONDITION_TO_VERIFY = "CONDITION_TO_VERIFY"
    REVIEW_QUESTION = "REVIEW_QUESTION"


class SubjectScope(str, Enum):
    USER = "USER"
    SITUATION = "SITUATION"
    PROCESS = "PROCESS"


class EpistemicBasis(str, Enum):
    CHART_EVIDENCE = "CHART_EVIDENCE"
    USER_PROVIDED_CONTEXT = "USER_PROVIDED_CONTEXT"
    ACTION_OPTION = "ACTION_OPTION"
    UNCERTAINTY = "UNCERTAINTY"


class KnowledgeEvidenceSourceType(str, Enum):
    APPROVED_HEXAGRAM_KNOWLEDGE = "APPROVED_HEXAGRAM_KNOWLEDGE"
    APPROVED_LINE_KNOWLEDGE = "APPROVED_LINE_KNOWLEDGE"
    REVIEWED_HEXAGRAM_PREVIEW = "REVIEWED_HEXAGRAM_PREVIEW"
    REVIEWED_LINE_PREVIEW = "REVIEWED_LINE_PREVIEW"
    DRAFT_HEXAGRAM_PREVIEW = "DRAFT_HEXAGRAM_PREVIEW"
    DRAFT_LINE_PREVIEW = "DRAFT_LINE_PREVIEW"


class NarrativeReleaseStatus(str, Enum):
    UNVERIFIED = "UNVERIFIED"
    INTERNAL_EVAL = "INTERNAL_EVAL"
    APPROVED_FOR_CLOSED_BETA = "APPROVED_FOR_CLOSED_BETA"
